### ISSUE TITLE
BUG : grafana-interacter didn't return error status when receiving error.

### ISSUE THREAD

**Issue by Femkecl** [freak12techno/grafana-interacter#1]
Details:
When rendering a panel and grafana-image-renderer fails (for example, in my case it was due to a missing library), the bot should send a message telling that a rendering error occured, however instead nothing is returned. The logs say the following:

Jun 14 19:31:39 snapshot-60806338-ubuntu-4gb-nbg1-1 grafana-interacter[52098]: 7:31PM TRC Doing a Grafana API query component=grafana method=GET url=http://localhost:3000/api/dashboards/uid/MsjffzSZz
Jun 14 19:31:39 snapshot-60806338-ubuntu-4gb-nbg1-1 grafana-interacter[52098]: 7:31PM TRC Doing a Grafana API query component=grafana method=GET url=http://localhost:3000/api/dashboards/uid/MBRTkBRZk
Jun 14 19:31:39 snapshot-60806338-ubuntu-4gb-nbg1-1 grafana-interacter[52098]: 7:31PM TRC Doing a Grafana API query component=grafana method=GET url=http://localhost:3000/api/dashboards/uid/rpfmFFz7z
Jun 14 19:31:39 snapshot-60806338-ubuntu-4gb-nbg1-1 grafana-interacter[52098]: 7:31PM TRC Doing a Grafana API query component=grafana method=GET url=http://localhost:3000/api/dashboards/uid/UDdpyzz7z
Jun 14 19:31:39 snapshot-60806338-ubuntu-4gb-nbg1-1 grafana-interacter[52098]: 7:31PM TRC Doing a Grafana API query component=grafana method=GET url=http://localhost:3000/api/dashboards/uid/PdqxY_y7k
Jun 14 19:31:39 snapshot-60806338-ubuntu-4gb-nbg1-1 grafana-interacter[52098]: 7:31PM TRC Doing a Grafana API query component=grafana method=GET url=http://localhost:3000/api/dashboards/uid/rYdddlPWk
Jun 14 19:31:39 snapshot-60806338-ubuntu-4gb-nbg1-1 grafana-interacter[52098]: 7:31PM TRC Doing a Grafana API query component=grafana method=GET url=http://localhost:3000/api/dashboards/uid/UJyurCTWz
Jun 14 19:31:39 snapshot-60806338-ubuntu-4gb-nbg1-1 grafana-interacter[52098]: 7:31PM TRC Doing a Grafana API query component=grafana method=GET url=http://localhost:3000/api/dashboards/uid/9nXvbXO7z
Jun 14 19:31:39 snapshot-60806338-ubuntu-4gb-nbg1-1 grafana-interacter[52098]: 7:31PM TRC Doing a Grafana API query component=grafana method=GET url=http://localhost:3000/render/d-solo/blackbox/dashboard?orgId=1&from=now&to=now-30m&widt>
Jun 14 19:31:39 snapshot-60806338-ubuntu-4gb-nbg1-1 grafana-interacter[52098]: 7:31PM ERR Telebot error error="telebot: unsupported what argument"

**Comment by freak12techno** [comment]
For myself, to not forget: when grafana image renderer fails (even with 4xx/5xx), it somehow doesn't send the message like "rendering failed, see logs" to a user.
