### ISSUE TITLE
Add other configurations to config file

### ISSUE THREAD

**Issue by RodrigoPina407** [freak12techno/grafana-interacter#20]
I want to set default configurations like the from and to on the config file but it does not seem to work

**Comment by freak12techno** [comment]
@RodrigoPina407 can you elaborate a bit further? I am not quite following what is missing

**Comment by RodrigoPina407** [comment]
for example instead of doing `/render from=now-3h to=now <panel>` I'd like to put those time range configs as default in the config file. It is possible to specify the timezone but I can't seem to specify the time range

**Comment by freak12techno** [comment]
Ah ok, got it. Sounds reasonable, will add a bit later.

**Comment by RodrigoPina407** [comment]
Thank you 👍

**Comment by freak12techno** [comment]
Hey @RodrigoPina407, so I created a PR to fix this. Can you try building grafana-interacter from the PR branch and check if it works for you? There's a config.example.yml to take for reference on how to set these values.

**Comment by RodrigoPina407** [comment]
yup, it's working fine 👍

**Comment by freak12techno** [comment]
@RodrigoPina407 jfyi I just pushed v2.0.0 release with this change, so now you can use a prebuilt package if you want. Seems to be all done here. Cheers!
