### ISSUE TITLE
Is it possible to authenticate with a service account?

### ISSUE THREAD

**Issue by RodrigoPina407** [freak12techno/grafana-interacter#34]
with the bearer token to be more specific, to set as the Authorization header instead of the basic auth

**Comment by RodrigoPina407** [comment]
with the bearer token to be more specific

**Comment by freak12techno** [comment]
@RodrigoPina407 it uses basic auth (https://github.com/freak12techno/grafana-interacter/blob/main/pkg/grafana/grafana.go#L303C7-L303C19), as in login/password, for queries, but adding a service account support shouldn't be that difficult actually. I haven't worked with service accounts before though, do you only need to pass Bearer token as authorization header?

**Comment by RodrigoPina407** [comment]
Yes. Basically just the Auth header in the format "Bearer <service account token>". I think that should be enough instead of the login and password

**Comment by freak12techno** [comment]
Yeah I can add it. Will do it some time. Thanks for reporting!

**Comment by freak12techno** [comment]
@RodrigoPina407 okay I did the PR that should introduce Grafana authorization via bearer auth. I unfortunately cannot test it on my own, can you build grafana-interacter from the branch from the PR and try verifying if it works for you?

**Comment by RodrigoPina407** [comment]
yes I will do that 👍

**Comment by freak12techno** [comment]
@RodrigoPina407 I just released 2.7.0 which includes this change so you can now download a binary instead of building from branch. Thanks for reporting and for debugging!
